version: '3.8'
services:
  app:
    build: .
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://localhost:27017
      - DB_NAME=blogs-db-dev
      - COLLECTION_NAME=blogs-db
      - JWT_SECRET=dev-secret
      - PORT=8080
    ports:
      - "8080:8080"
